stages:
  - build
  - deploy
  - test
  - release

build_binary: 
  image: chusiang/ansible:alpine-3.6
  stage: build
  script:
    - echo "fake build"
  tags:
      - docker

deploy_to_development: 
  image: chusiang/ansible:alpine-3.6
  stage: deploy
  script:
    - echo "fake deploy"
  tags:
      - docker

test_development: 
  image: chusiang/ansible:alpine-3.6
  stage: test
  script:
    - echo "fake test"
  tags:
      - docker

release_to_production: 
  image: chusiang/ansible:alpine-3.6
  stage: release
  script:
    - echo "fake release"
  tags:
      - docker
  when: manual

# vim: ft=yaml :
