stages:
  - build
  - deploy
  - test
  - release

build: 
  image: chusiang/ansible:alpine-3.6
  stage: build
  script:
    - echo "fake build"
  tags:
      - docker

deploy: 
  image: chusiang/ansible:alpine-3.6
  stage: deploy
  script:
    - echo "fake deploy"
  tags:
      - docker

test: 
  image: chusiang/ansible:alpine-3.6
  stage: test
  script:
    - echo "fake test"
  tags:
      - docker

release: 
  image: chusiang/ansible:alpine-3.6
  stage: release
  script:
    - echo "fake release"
  tags:
      - docker
