#!/usr/bin/env ansible-playbook
# ============================================================
#  Author: Chu-Siang Lai / chusiang (at) drx.tw
#  Blog: http://note.drx.tw
#  Filename: deploy.yml
#  Modified: 2017-08-01 23:27
#  Description: deploy application with ansible.
# ===========================================================
---

- name: ==> Deploying ...
  hosts: all

  # Tasks
  #######

  tasks:
    - name: uninstall penguin-htdocs package
      become: true
      apt:
        name: penguin-htdocs
        state: absent

    - name: copy deb file to managed node
      copy:
        src: ../penguin-htdocs.deb
        dest: /tmp/

    - name: install package via deb file
      become: true
      apt:
        deb: /tmp/penguin-htdocs.deb

    - name: remove deb file
      file:
        path: /tmp/penguin-htdocs.deb
        state: absent

    - name: 'start nginx'
      become: true
      service:
        name: 'nginx'
        state: 'started'

  post_tasks:
    # 冒煙測試。
    - name: smoke testing
      import_tasks: tasks/verify.yml

# vim: ft=ansible :
