#!/usr/bin/env ansible-playbook
# ============================================================
#  Author: Chu-Siang Lai / chusiang (at) drx.tw
#  Blog: http://note.drx.tw
#  Filename: setup.yml
#  Modified: 2017-08-01 00:53
#  Description: setup with ansible.
#
#   Setup = Provision + Deployment .
#
# ===========================================================
---

# Provision
- name: import provision playbook
  import_playbook: provision.yml

# Deployment
- name: import deployment playbook
  import_playbook: deploy.yml

# vim: ft=ansible :
