# -*- mode: ruby -*-

# Setup Python 2 for Ubuntu 16.04 .
$script = <<SCRIPT
sudo sed -i 's/archive.ubuntu.com/free.nchc.org.tw/g' /etc/apt/sources.list
sudo apt-get update && sudo apt-get install -y python
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 10080

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.provision "shell", inline: $script

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
    ansible.become = true
  end

end

# vi: set ft=ruby :
